#SpringBoot默认的Yaml配置文件

#设置应用程序端口
server:
  port: 8080

##########应用程序配置##########
spring:
##########配置文件相关配置##########
# 设置生效的配置文件
  profiles:
    active: dev

##########数据库相关配置##########
  datasource:
    password: 123456
    username: root
#连接到docker中的MySQL
    url: jdbc:mysql://111.230.169.249:3307/springboot
#设置执行的脚本文件
#    schema:
#     - classpath:employee.sql
#     - classpath:department.sql
#设置datasource为Druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
#数据源其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
#配置监控统计拦截的filters，去掉后监控界面sql无法统计
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true

##########JPA相关配置##########
  jpa:
    hibernate:
#自动创建或更新数据表
      ddl-auto: update
#控制台显示sql
    show-sql: true


##########是否启动Debug模式##########
# 启动debug模式可以打印出自动匹配报告，列出已启用的自动配置
#debug: true


##########日志相关配置##########
logging:
  file:
#指定日志路径
    path: D:\
#设置日志级别
  level.com.shl: debug


##########Mybatis相关配置##########
#配置mybatis配置文件路径和mapper路径
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml


##########配置一个Bean的属性##########
#${} 括号中可以解析表达式， 冒号:可以加一个默认值,如果前面表达式不能解析，那么会使用默认值
person:
 name: liming
 age: ${person.dog.age:10000}
 sex: 1
 email: shenghail@qq.com
 list:
  - lisi
  - zhangsan
 map: {key1: val1, key2: val2}
 dog:
  name: 小黑
  age: 2

